### ISSUE TITLE
Piwik Analytics

### ISSUE THREAD

**Issue by MarauderXtreme** [kiliankoe/kilian.io#1]
Recently I've seen that Ghostery is blocking a tracker on your site. You're using Piwik but you have no opt-out and no hint on your site. I would like to warn you because a bad person could cause trouble because of this. You need at least some kind of warning bar on your site. (Maybe like google) In Germany you are required to warn your visitors and make an opt-out available.
Maybe have a look at [this](https://www.datenschutzbeauftragter-info.de/fachbeitraege/piwik-datenschutzkonform-einsetzen/)

**Comment by kiliankoe** [comment]
Point taken, not really using it anymore anyways. Kicked it. Thanks :)
